### ISSUE TITLE
code does not match worksheet description

### ISSUE THREAD

**Issue by jonwitts** [raspberrypilearning/sense-hat-cheerlights#1]
The Sense Hat Cheerlights project https://projects.raspberrypi.org/en/projects/sense-hat-cheerlights links to the cheerlights.py file in this repo and states "The starter code simply prints out the tweet contents. Press the Run button and get someone to tweet #cheerlights red — you should see the word ‘red’ in the output." However this file is the completed version from the worksheet. Does it need adjusting?

**Comment by martinohanlon** [comment]
@bennuttall you ok to investigate?

**Comment by bennuttall** [comment]
Will do :+1:

**Comment by bennuttall** [comment]
Thanks @jonwitts, you're right, I must have committed the finished version by mistake. Does this version look right to you, as starter code? https://github.com/raspberrypilearning/sense-hat-cheerlights/blob/master/en/resources/cheerlights.py
